export const TICKERS = {
  AEM: {
    name: "Agnico Eagle Mines",
    company: "Agnico Eagle Mines Limited",
    metal: "gold",
    type: "producer",
    aliases: ["Agnico Eagle", "Agnico Eagle Mines Limited"],
    q: '(AEM OR "Agnico Eagle" OR "Agnico Eagle Mines") (gold OR mining OR earnings OR production)',
  },
  NEM: {
    name: "Newmont",
    company: "Newmont Corporation",
    metal: "gold",
    type: "producer",
    aliases: ["Newmont", "Newmont Corporation"],
    q: '(NEM OR "Newmont" OR "Newmont Corporation") (gold OR mining OR earnings OR production)',
  },
  GOLD: {
    name: "Barrick Gold",
    company: "Barrick Gold Corporation",
    metal: "gold",
    type: "producer",
    aliases: ["Barrick", "Barrick Gold", "Barrick Gold Corporation"],
    q: '(GOLD OR "Barrick" OR "Barrick Gold") (gold OR mining OR earnings OR production)',
  },
  KGC: {
    name: "Kinross Gold",
    company: "Kinross Gold Corporation",
    metal: "gold",
    type: "producer",
    aliases: ["Kinross", "Kinross Gold"],
    q: '(KGC OR "Kinross" OR "Kinross Gold") (gold OR mining OR earnings)',
  },
  AU: {
    name: "AngloGold Ashanti",
    company: "AngloGold Ashanti plc",
    metal: "gold",
    type: "producer",
    aliases: ["AngloGold", "Anglogold Ashanti", "AngloGold Ashanti"],
    q: '(AU OR "AngloGold" OR "AngloGold Ashanti") (gold OR mining OR earnings)',
  },
  BTG: {
    name: "B2Gold",
    company: "B2Gold Corp.",
    metal: "gold",
    type: "producer",
    aliases: ["B2Gold", "B2 Gold"],
    q: '(BTG OR "B2Gold" OR "B2 Gold") (gold OR mining OR earnings)',
  },
  AGI: {
    name: "Alamos Gold",
    company: "Alamos Gold Inc.",
    metal: "gold",
    type: "producer",
    aliases: ["Alamos", "Alamos Gold"],
    q: '(AGI OR "Alamos" OR "Alamos Gold") (gold OR mining OR earnings)',
  },
  GFI: {
    name: "Gold Fields",
    company: "Gold Fields Limited",
    metal: "gold",
    type: "producer",
    aliases: ["Gold Fields", "Gold Fields Limited"],
    q: '(GFI OR "Gold Fields" OR "Gold Fields Limited") (gold OR mining OR earnings)',
  },
  HMY: {
    name: "Harmony Gold",
    company: "Harmony Gold Mining Company Limited",
    metal: "gold",
    type: "producer",
    aliases: ["Harmony", "Harmony Gold", "Harmony Gold Mining"],
    q: '(HMY OR "Harmony Gold" OR "Harmony Gold Mining") (gold OR mining OR earnings)',
  },
  OR: {
    name: "Osisko Gold Royalties",
    company: "Osisko Gold Royalties Ltd",
    metal: "gold",
    type: "royalty",
    aliases: ["Osisko", "Osisko Gold Royalties"],
    q: '(OR OR "Osisko" OR "Osisko Gold Royalties") (gold OR royalty OR mining)',
  },
  FNV: {
    name: "Franco-Nevada",
    company: "Franco-Nevada Corporation",
    metal: "gold",
    type: "royalty",
    aliases: ["Franco Nevada", "Franco-Nevada"],
    q: '(FNV OR "Franco Nevada" OR "Franco-Nevada") (gold OR royalty OR mining)',
  },
  RGLD: {
    name: "Royal Gold",
    company: "Royal Gold, Inc.",
    metal: "gold",
    type: "royalty",
    aliases: ["Royal Gold", "Royal Gold Inc"],
    q: '(RGLD OR "Royal Gold") (gold OR royalty OR mining)',
  },
  PZG: {
    name: "Paramount Gold Nevada",
    company: "Paramount Gold Nevada Corp.",
    metal: "gold",
    type: "developer",
    aliases: ["Paramount Gold", "Paramount Gold Nevada"],
    q: '(PZG OR "Paramount Gold" OR "Paramount Gold Nevada") (gold OR mining)',
  },
  GAYMF: {
    name: "Galiano Gold",
    company: "Galiano Gold Inc.",
    metal: "gold",
    type: "producer",
    aliases: ["Galiano", "Galiano Gold"],
    q: '(GAYMF OR "Galiano" OR "Galiano Gold") (gold OR mining OR earnings)',
  },
  HYMC: {
    name: "Hycroft Mining",
    company: "Hycroft Mining Holding Corporation",
    metal: "gold",
    type: "developer",
    aliases: ["Hycroft", "Hycroft Mining"],
    q: '(HYMC OR "Hycroft" OR "Hycroft Mining") (gold OR silver OR mining OR earnings)',
  },

  WPM: {
    name: "Wheaton Precious Metals",
    company: "Wheaton Precious Metals Corp.",
    metal: "silver",
    type: "royalty",
    aliases: ["Wheaton", "Wheaton Precious Metals"],
    q: '(WPM OR "Wheaton" OR "Wheaton Precious Metals") (silver OR gold OR royalty OR mining OR earnings)',
  },
  PAAS: {
    name: "Pan American Silver",
    company: "Pan American Silver Corp.",
    metal: "silver",
    type: "producer",
    aliases: ["Pan American", "Pan American Silver"],
    q: '(PAAS OR "Pan American" OR "Pan American Silver") (silver OR mining OR earnings)',
  },
  AG: {
    name: "First Majestic Silver",
    company: "First Majestic Silver Corp.",
    metal: "silver",
    type: "producer",
    aliases: ["First Majestic", "First Majestic Silver"],
    q: '(AG OR "First Majestic" OR "First Majestic Silver") (silver OR mining OR earnings)',
  },
  MAG: {
    name: "MAG Silver",
    company: "MAG Silver Corp.",
    metal: "silver",
    type: "developer",
    aliases: ["MAG Silver", "MAG Silver Corp"],
    q: '(MAG OR "MAG Silver") (silver OR mining OR earnings)',
  },
  CDE: {
    name: "Coeur Mining",
    company: "Coeur Mining, Inc.",
    metal: "silver",
    type: "producer",
    aliases: ["Coeur", "Coeur Mining"],
    q: '(CDE OR "Coeur" OR "Coeur Mining") (silver OR gold OR mining OR earnings)',
  },
  HL: {
    name: "Hecla Mining",
    company: "Hecla Mining Company",
    metal: "silver",
    type: "producer",
    aliases: ["Hecla", "Hecla Mining"],
    q: '(HL OR "Hecla" OR "Hecla Mining") (silver OR gold OR mining OR earnings)',
  },
  EXK: {
    name: "Endeavour Silver",
    company: "Endeavour Silver Corp.",
    metal: "silver",
    type: "producer",
    aliases: ["Endeavour Silver", "Endeavour"],
    q: '(EXK OR "Endeavour Silver" OR "Endeavour") (silver OR mining OR earnings)',
  },
  SVM: {
    name: "Silvercorp Metals",
    company: "Silvercorp Metals Inc.",
    metal: "silver",
    type: "producer",
    aliases: ["Silvercorp", "Silvercorp Metals"],
    q: '(SVM OR "Silvercorp" OR "Silvercorp Metals") (silver OR mining OR earnings)',
  },
  SILV: {
    name: "SilverCrest Metals",
    company: "SilverCrest Metals Inc.",
    metal: "silver",
    type: "developer",
    aliases: ["SilverCrest", "SilverCrest Metals"],
    q: '(SILV OR "SilverCrest" OR "SilverCrest Metals") (silver OR mining OR earnings)',
  },
  DSVSF: {
    name: "Discovery Silver",
    company: "Discovery Silver Corp.",
    metal: "silver",
    type: "developer",
    aliases: ["Discovery Silver", "Discovery"],
    q: '(DSVSF OR "Discovery Silver" OR "Discovery") (silver OR mining OR earnings)',
  },

  FCX: {
    name: "Freeport-McMoRan",
    company: "Freeport-McMoRan Inc.",
    metal: "copper",
    type: "producer",
    aliases: ["Freeport", "Freeport McMoRan", "Freeport-McMoRan"],
    q: '(FCX OR "Freeport" OR "Freeport McMoRan" OR "Freeport-McMoRan") (copper OR mining OR earnings)',
  },
  SCCO: {
    name: "Southern Copper",
    company: "Southern Copper Corporation",
    metal: "copper",
    type: "producer",
    aliases: ["Southern Copper", "Southern Copper Corporation"],
    q: '(SCCO OR "Southern Copper") (copper OR mining OR earnings)',
  },
  TECK: {
    name: "Teck Resources",
    company: "Teck Resources Limited",
    metal: "copper",
    type: "producer",
    aliases: ["Teck", "Teck Resources"],
    q: '(TECK OR "Teck" OR "Teck Resources") (copper OR zinc OR mining OR earnings)',
  },
  HBM: {
    name: "Hudbay Minerals",
    company: "Hudbay Minerals Inc.",
    metal: "copper",
    type: "producer",
    aliases: ["Hudbay", "Hudbay Minerals"],
    q: '(HBM OR "Hudbay" OR "Hudbay Minerals") (copper OR mining OR earnings)',
  },
  TRQ: {
    name: "Turquoise Hill",
    company: "Turquoise Hill Resources Ltd.",
    metal: "copper",
    type: "developer",
    aliases: ["Turquoise Hill", "Oyu Tolgoi"],
    q: '(TRQ OR "Turquoise Hill" OR "Oyu Tolgoi") (copper OR mining)',
  },
  TGB: {
    name: "Taseko Mines",
    company: "Taseko Mines Limited",
    metal: "copper",
    type: "producer",
    aliases: ["Taseko", "Taseko Mines"],
    q: '(TGB OR "Taseko" OR "Taseko Mines") (copper OR mining OR earnings)',
  },

  LUCRF: {
    name: "Lucara Diamond",
    company: "Lucara Diamond Corp.",
    metal: "diamond",
    type: "producer",
    aliases: ["Lucara", "Lucara Diamond", "Lucara Diamond Corp"],
    q: '(LUCRF OR "Lucara" OR "Lucara Diamond") (diamond OR mining OR production)',
  },
  MPVDF: {
    name: "Mountain Province Diamonds",
    company: "Mountain Province Diamonds Inc.",
    metal: "diamond",
    type: "producer",
    aliases: ["Mountain Province", "Mountain Province Diamonds"],
    q: '(MPVDF OR "Mountain Province" OR "Mountain Province Diamonds") (diamond OR mining OR production)',
  },
  NGLOY: {
    name: "Anglo American",
    company: "Anglo American plc",
    metal: "diamond",
    type: "diamond-related",
    aliases: ["Anglo American", "De Beers", "DeBeers"],
    q: '(NGLOY OR "Anglo American" OR "De Beers" OR "DeBeers") (diamond OR mining)',
  },
  RIO: {
    name: "Rio Tinto",
    company: "Rio Tinto Group",
    metal: "diamond",
    type: "diamond-related",
    aliases: ["Rio Tinto", "Diavik", "diamond mining"],
    q: '(RIO OR "Rio Tinto" OR "Diavik") (diamond OR copper OR mining)',
  },

  PSLV: {
    name: "Sprott Physical Silver Trust",
    company: "Sprott Physical Silver Trust",
    metal: "silver",
    type: "fund",
    aliases: ["PSLV", "Sprott Physical Silver Trust", "Sprott silver"],
    q: '(PSLV OR "Sprott Physical Silver Trust" OR "Sprott silver") (silver OR trust OR ETF OR fund)',
  },
  SIL: {
    name: "Global X Silver Miners ETF",
    company: "Global X Silver Miners ETF",
    metal: "silver",
    type: "etf",
    aliases: ["SIL ETF", "Global X Silver Miners", "silver miners ETF"],
    q: '(SIL OR "Global X Silver Miners" OR "silver miners ETF") (ETF OR fund OR holdings)',
  },
  SILJ: {
    name: "Amplify Junior Silver Miners ETF",
    company: "Amplify Junior Silver Miners ETF",
    metal: "silver",
    type: "etf",
    aliases: ["SILJ", "junior silver miners ETF", "Amplify Junior Silver Miners"],
    q: '(SILJ OR "Amplify Junior Silver Miners" OR "junior silver miners ETF") (ETF OR fund OR holdings)',
  },
  SIVR: {
    name: "abrdn Physical Silver Shares",
    company: "abrdn Physical Silver Shares ETF",
    metal: "silver",
    type: "etf",
    aliases: ["SIVR", "abrdn Physical Silver Shares", "SIVR ETF"],
    q: '(SIVR OR "abrdn Physical Silver Shares" OR "SIVR ETF") (silver OR ETF OR fund)',
  },
  SLV: {
    name: "iShares Silver Trust",
    company: "iShares Silver Trust",
    metal: "silver",
    type: "etf",
    aliases: ["SLV ETF", "iShares Silver Trust", "silver ETF SLV"],
    q: '(SLV OR "iShares Silver Trust" OR "silver ETF SLV") (silver OR ETF OR fund)',
  },
};
